### ISSUE TITLE
Client secret expires in...?

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1083]
Steps:

1. Log in to the Gluu Server
2. Go to OpenID Connect -> Clients -> Add Client
3. Fill in the required fields, ignore the "Client's Registration Expires" field 
4. Click on Add
5. Click on the name of the newly created client
6. Inspect the details

Expected: As a user I want to be able to see the set client registration expiration date, especially if I overlook it and a default value is set upon creating a new client.
Actual: There's no expiration date visible.
The UX would greatly benefit from the visibility of the expiration date.

**Comment by syntrydy** [comment]
@natt-tester i thibk this issue is fixed here https://github.com/GluuFederation/oxTrust/issues/1080

**Comment by natt-tester** [comment]
@syntrydy, the issue is still present in the latest RC2 package. After ignoring the date picker and creating a new client, the expiration date is not present in the GUI:

<img width="710" alt="ubuntu16_disappearing" src="https://user-images.githubusercontent.com/38302725/45073285-eb07e380-b121-11e8-80e3-63eea06ca3a6.png">

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45110789-2d89ea00-b13b-11e8-82f3-1d61f43ea6a7.png)
