### ISSUE TITLE
Failed to start redisProvider

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#1994]
I am little confused if I should open this such issue under oxAuth or oxTrust. But, I can't setup external Redis Cache in 4.2. 
Here is the testing situation: https://youtu.be/bTfRNttrf2k

**Comment by yuriyz** [comment]
@mzico Got it, moved to oxTrust project and assigned to @syntrydy to check.

**Comment by syntrydy** [comment]
@mzico how can i replicate this?

**Comment by mzico** [comment]
@syntrydy : my procedure is added in [this](https://github.com/GluuFederation/oxTrust/issues/1994#issuecomment-653773101) comment. I have a redis server in cloud, if you want.. I can fire up that machine for your testing.

**Comment by syntrydy** [comment]
@mzico In my case i was able to connect to redis. Please ive a try with the upcomming package. I changed the code to provide more information about the error.

**Comment by syntrydy** [comment]
@mzico This is now fixed

**Comment by mzico** [comment]
@syntrydy : Problem is still there in 4.2.0. 

As discussed this is what happening: https://youtu.be/ylSGA9Ro3H8

 - Whenever we are clear text password for redis configuration, it's working. 
 - After 'Update' / 'Save Configuration', oxTrust is encoding it. 
 - Encoded value looks good.. BUT
 - oxTrust can't deal with encoded redis password and hence it's failing to complete configuration.

**Comment by syntrydy** [comment]
@mzico i think you are not using that form as expected, to configure redis, 
![image](https://user-images.githubusercontent.com/7513418/87612701-2ce11800-c703-11ea-98df-d5a63726cb6b.png)
That is first step. In the video you don't select that.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/87666744-11a4f580-c761-11ea-9b20-204cbefbdfb3.png)
The password display on the UI is not the encoded password.

**Comment by mzico** [comment]
@syntrydy @yuriyz : thanks for the fix in 4.2. Can we fix this in 3.1.8? As it's the last & long term version of v3, it will be great to have this fix here. Thoughts?

**Comment by syntrydy** [comment]
@mzico do you have a video showing the behavior in 3.1.8?

**Comment by mzico** [comment]
@syntrydy : I will prepare one and share...

**Comment by syntrydy** [comment]
@mzico okey

**Comment by mzico** [comment]
@syntrydy : [here](https://youtu.be/PSMihi5hzZ0) is the video.

**Comment by syntrydy** [comment]
@mzico i think it is better to create new issue and tag it 3.1.8

**Comment by mzico** [comment]
Done: https://github.com/GluuFederation/oxTrust/issues/2008
