### ISSUE TITLE
Password reset page is showing old GUI

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#215]
Screenshot attached of what we are getting with 2.4.2. We should push new oxTrust GUI in this page as well. 

![passwordresetpage](https://cloud.githubusercontent.com/assets/7156097/13742042/9a4ef72e-e9a7-11e5-8c6f-41a58e8b868b.png)

**Comment by willow9886** [comment]
@mzico any thoughts on who this should be assigned to?

**Comment by mzico** [comment]
@willow9886 : Yes, @shekhar16 would be good. If required, @qbert2k can assist, I believe.

**Comment by willow9886** [comment]
@shekhar16 can you take a look into this?

**Comment by shekhar16** [comment]
Fixed and the code is commited.

**Comment by mzico** [comment]
@shekhar16 : Here is what I can see the new password reset page. I think 'Set Password' and 'Cancel' are still showing green instead of our new blue color. Plus... 'Set Password' and 'Cancel' buttons should be under Captcha box? 

![passresetlink](https://cloud.githubusercontent.com/assets/7156097/14156883/3fc5dafe-f68e-11e5-9a18-df259ecb9ca6.png)

**Comment by shekhar16** [comment]
Fixed and code is committed.

**Comment by willow9886** [comment]
@shekhar16 can we also use [recaptcha](https://www.google.com/recaptcha/intro/index.html) here instead of regular captcha?

**Comment by shekhar16** [comment]
Yeah ,I am looking into it.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/14293774/a1d79866-fb8b-11e5-9993-04660e2eae5b.png)

**Comment by shekhar16** [comment]
Fixed. New Recaptcha is implemented.

**Comment by mzico** [comment]
@shekhar16 I tried to implement this in one server with 'oxtrust-server-2.4.3-SNAPSHOT.war'. Getting below error whenever I am trying to use 'reset password' feature. 

![recaptcha](https://cloud.githubusercontent.com/assets/7156097/14295535/aaf2c556-fb3b-11e5-93f0-c60a90c6d79f.png)

Might be helpful on this error with reCaptcha, a link: http://stackoverflow.com/questions/30735694/recaptcha-error-invalid-domain-for-site-key

**Comment by shekhar16** [comment]
@mzico  We need to create the site key and secret key from google recaptcha for the our specific domain which we are using .Please share domain name, i will try to register and generate the keys from https://www.google.com/recaptcha/admin#list

**Comment by mzico** [comment]
@shekhar16 : domain name: https://idp.gluu.org

**Comment by shekhar16** [comment]
@mzico Domain added.

**Comment by yurem** [comment]
yes, domain added. But we need to wait once @shekhar16 will move server key to oxTrust settings. Now we uses my tests account...

**Comment by shekhar16** [comment]
The corrections are done.Please add properties in oxtrustConfApplication
,
	"recaptchUrl": "https://www.google.com/recaptcha/api/siteverify",
	"recaptchaSiteKey": "6LcYpRsTAAAAAFqRBoHmjJEE72-0Ey-GbZV-6vqC",
	"recaptchaSecretKey": "6LcYpRsTAAAAAEnaFe4KFkwQ6GzyZqEZ2fcs4SNq"

**Comment by mzico** [comment]
It's resolved.
