### ISSUE TITLE
Client Form boolean select boxes should not default to true

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#270]
There is a problem with this form. The default for booleans should not be true. 

For example, persist authorizations should be either empty (no value) or false. By making the default true, it changes the behavior of the client even if nothing changed.

![image](https://cloud.githubusercontent.com/assets/3717101/15797049/139cf19e-29d1-11e6-8af8-b95993dc9956.png)

Just by hitting update, I see the following values were added to the client entry:

    oxAuthLogoutSessionRequired: true
    oxAuthRequireAuthTime: true
    oxPersistClientAuthorizations: true

**Comment by yurem** [comment]
@zamilskhan Also QA should add one more test:
1) export client entry to ldif
2) Open form for update but du nothing and just click update
3) export client entry to another ldif
4) compare both ldifs

Same test we should do for all other objects too.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/15831867/4c5c18ca-2c3d-11e6-97f0-03dd11b070c1.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by mzico** [comment]
@shekhar16 : I can still see 'True' in drop down menu. 

oxTrust version: 

Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.3-SNAPSHOT
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 9c43b
Archiver-Version: Plexus Archiver

![persist_client_authorizations](https://cloud.githubusercontent.com/assets/7156097/16013562/88c9e376-3153-11e6-9a5a-7065cc348c9d.png)

**Comment by willow9886** [comment]
Looks good, Shekhar. Thanks
