### ISSUE TITLE
It's impossible to remove entries from "Logout URI" property of OIDC client.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#366]
Environment:
CentOS 6.7, Gluu CE 2.4.4 SP2, Firefox 49.0.2

Steps to reproduce:
1. Log in to web UI as admin
2. Move to "OpenID -> Client" page
3. Create some basic client registration of type "Web" providing minimal set of required settings; make sure to set "Logout session required" to "True"; add some [bogus] uri as logout uri (by clicking "Add Logout URI" button); click "Update" button
4. Try to remove "Logout URI" you added before by clicking little cross button to the right of it

Result:
User is redirected to home page and "System error" message appears. Java exception is registered to `wrapper.log` ( [here is full text of it](https://github.com/GluuFederation/oxTrust/files/511883/logouturi_remove_exception.txt) ):

```
INFO   | jvm 1    | 2016/10/05 17:10:36 | Oct 05, 2016 5:10:36 PM com.sun.faces.lifecycle.InvokeApplicationPhase execute
INFO   | jvm 1    | 2016/10/05 17:10:36 | WARNING: #{_clientAction.removeNewLogoutURI(_uri)}: javax.el.MethodNotFoundException: //localhost/identity/WEB-INF/incl/client/clientForm.xhtml @391,235 action="#{_clientAction.removeNewLogoutURI(_uri)}": Method not found: org.gluu.oxtrust.action.UpdateClientAction@7b9fbcf4.removeNewLogoutURI(java.lang.String)
INFO   | jvm 1    | 2016/10/05 17:10:36 | javax.faces.FacesException: #{_clientAction.removeNewLogoutURI(_uri)}: javax.el.MethodNotFoundException: //localhost/identity/WEB-INF/incl/client/clientForm.xhtml @391,235 action="#{_clientAction.removeNewLogoutURI(_uri)}": Method not found: org.gluu.oxtrust.action.UpdateClientAction@7b9fbcf4.removeNewLogoutURI(java.lang.String)
INFO   | jvm 1    | 2016/10/05 17:10:36 |   at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:109)
INFO   | jvm 1    | 2016/10/05 17:10:36 |   at javax.faces.component.UICommand.broadcast(UICommand.java:315)
```

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/19215337/e6768788-8db8-11e6-88c3-ad1cf598938e.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/19215344/113c978c-8db9-11e6-9d9a-e766b5750472.png)

**Comment by shekhar16** [comment]
Hi @aliaksander-samuseu 
It is working on ce-dev  and my local env.
I m not able to reproduce it please let me know if i missed something.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

Not sure why/in which package you can't reproduce it. Still is easily triggered in CentOS6.7 Gluu CE 2.4.4 + SP2 (see attached picture). I also think fix for this one should too be a candidate to be pushed into SP2 for 2.4.4 packages.

**Comment by shekhar16** [comment]
Sorry @aliaksander-samuseu  I tested again in my local with latest code and on ce-dev env aswel i.e. https://ce-dev.gluu.org/identity and found it is working fine.please try on https://ce-dev.gluu.org/identity env.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

I'm testing in my own local instance. You can see environment described at the start of the report

**Comment by nynymike** [comment]
@aliaksander-samuseu can you re-test and close this issue if you can't replicate?

**Comment by shekhar16** [comment]
@aliaksander-samuseu @nynymike 
the issue is fixed in below issue
https://github.com/GluuFederation/oxTrust/issues/321
And @aliaksander-samuseu yes this issue exist in sp2 version but Please confirm fixes included in sp2 version.
@nynymike I think sp2 involves only specific functionalities and fixes, it doesn't contains latest code present at build time.

**Comment by yurem** [comment]
Now remove buttons calls right method

**Comment by aliaksander-samuseu** [comment]
Reopening.
It works fine in 3.0.x CE, but I still can't confirm it works in latest 2.4.4.2 packages available in repos. Tested for gluu-server-2.4.4.2_6-1~trusty+Ub14.04_amd64.deb from 2016-11-07, and the issue is still there. Shouldn't it be also fixed in SP2? If it wasn't added to it, then it should be candidate for SP3.

**Comment by mzico** [comment]
@aliaksander-samuseu : It's working in 2.4.4.2 ( ** ) version. Please validate. 

(**) 

```
GLUU.root@idp:~# cat /opt/tomcat/webapps/oxauth/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxAuth Server
Implementation-Version: 2.4.4.sp3
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: a4faf1c8915c628e5d3826cbf7bb5923f9dd3eea
Archiver-Version: Plexus Archiver

GLUU.root@idp:~# cat /opt/tomcat/webapps/identity/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.4.sp2
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: bcdae
Archiver-Version: Plexus Archiver

GLUU.root@idp:~#
```

**Comment by shekhar16** [comment]
Fixed.
