### ISSUE TITLE
Duplicate Messages in oxTrust

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#375]
Error and success messages are being duplicated when I update cache refresh. Also, the messages disappear too quickly, sometimes before I can read them. 

![image](https://cloud.githubusercontent.com/assets/3717101/19496167/f1689984-954b-11e6-9348-eeda4ff1f07c.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/commit/0ca0db19c6c9ebd8001c0ad26cb2e3da9bc35036

Fixed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/20808476/c44541fa-b828-11e6-871d-f4f22c127d33.png)

**Comment by shekhar16** [comment]
Fixed.

**Comment by yurem** [comment]
There is only one message in latest 3.0.0 build

**Comment by sahiliamsso** [comment]
Still see duplicate error messages. We'd need to check on other screens too.

![image](https://cloud.githubusercontent.com/assets/21104811/21557325/cbfb7b38-ce50-11e6-8ca3-c2ed69236c98.png)

**Comment by aliaksander-samuseu** [comment]
Can't see duplicated messages on Cache Refresh pages any more, but on attribute register page those error messages Sahil reported above still are present in the latest Ubuntu 14 dev package.

**Comment by worm333** [comment]
Removed *rich:notifyMessages* tag from templates/views that cause duplications. See [this](https://github.com/GluuFederation/oxTrust/pull/445) pull request.
