### ISSUE TITLE
Wrong name is displayed for backend in "Change password" dialogue

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#376]
Environment: Gluu CE 2.4.4 SP1

Preconditions:
2 different backends are configured for CR (no need to actually have real hosts as such, just providing random values is enough)

Steps to reproduce:
1. Log in as admin to web UI
2. Move to "Cache refresh", "Source backend LDAP servers" tab
3. Click "Change bind password" link of the 1st backend

Result:
No backend name is displayed in the pop-up "Change password" dialog window. If you try to set some password using it and click "Update" button, then after configuration is updated will move to this tab again, and start clicking  "Change bind password" links for both backends again, you'll see that the same name is displayed now for both of them, it's either the name of the backend which link you clicked first, or the last backend you updated configuration for (not sure). The actual functionality works correct, though, i.e. it updates password for the correct backend. Seems it's just issue with displayed text. Please see picture below.

Expected result:
Name of the backend to which clicked link belongs is displayed in the caption

![cr_pass_reset_cap](https://cloud.githubusercontent.com/assets/11802046/19503722/3ad6611a-95be-11e6-8731-76644f11987e.jpg)

**Comment by shekhar16** [comment]
@aliaksander-samuseu It is working in my local.please see below image

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/19564840/804da5f6-9702-11e6-9e5f-d7145f7c03d9.png)

**Comment by aliaksander-samuseu** [comment]
Have you tried to create 2 backends with different names and click links for both?

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

Could you confirm you tested it for 2 backend configurations named differently?

**Comment by shekhar16** [comment]
Yes @aliaksander-samuseu , it was an issue. 
It is fixed now , please test it with updated build.
Thanks :)

**Comment by aliaksander-samuseu** [comment]
@shekhar16 

I still see it in my CentOS6 instance updated to latest SP2 patch package. Do you think we could also include this fix into SP2 which is currently in QA stage?

**Comment by shekhar16** [comment]
@aliaksander-samuseu @nynymike it is already fix and working with latest code.
I think in 2.4.4 sp versions are specific to few fixes it doesn't contains the latest code base at release time.

**Comment by shekhar16** [comment]
@aliaksander-samuseu Please verify it  and close it, or if any issue found please assign back to me.

**Comment by nynymike** [comment]
Closing it. It can be retested on regression testing phase.
