### ISSUE TITLE
"Add user" feature of web UI fails

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#381]
Environment:
Gluu CE 2.4.4 SP2, Ubuntu 14.04

Steps to reproduce:
1. Log in to web UI as admin
2. Click "Users -> Add person" link in the accordion menu to the left
3. Fill all fields with values similar to picture below:
![adduser_fails](https://cloud.githubusercontent.com/assets/11802046/19830924/267e1e32-9e07-11e6-9161-70932303c4c6.jpg)

Result:
New user isn't created. Browser is redirected to the home page where "System error.." message is displayed. Java exception is registered in `wrapper.log` (full text is [here](https://github.com/GluuFederation/oxTrust/files/560002/adduser_fail_log.txt)):

```
INFO   | jvm 1    | 2016/10/29 15:13:56 | Oct 29, 2016 3:13:56 PM com.sun.faces.lifecycle.InvokeApplicationPhase execute
INFO   | jvm 1    | 2016/10/29 15:13:56 | WARNING: #{updatePersonAction.save}: java.lang.NullPointerException
INFO   | jvm 1    | 2016/10/29 15:13:56 | javax.faces.FacesException: #{updatePersonAction.save}: java.lang.NullPointerException
INFO   | jvm 1    | 2016/10/29 15:13:56 |   at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:117)
INFO   | jvm 1    | 2016/10/29 15:13:56 |   at javax.faces.component.UICommand.broadcast(UICommand.java:315)
```

**Comment by shekhar16** [comment]
@aliaksander-samuseu it is occuring because the duplicate gluustatus attribute is not deleted properly.
It is fixed in latest version 3.0.0.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 
Not quite sure what do you mean by "duplicate gluustatus attribute", but it's still an issue in the latest instance (patched to SP2). Is it okay to leave it like this in 2.4.4? SP2 is in QA stage, so we still have a chance to push your fix in there, many users will probably still be using 2.4.4 for some time.

**Comment by willow9886** [comment]
We should definitely apply the patch to 2.4.4...

**Comment by mikevalstar** [comment]
I am having the same issue; fresh install of 2.4.4.2

**Comment by nynymike** [comment]
@shekhar16 can you check if this issue exists for 3.0?

**Comment by shekhar16** [comment]
@nynymike it is fixed.

**Comment by gdstr** [comment]
it's still a problem in 2.4.4.sp2 and also on a fresh Ubuntu 16.04 install.

**Comment by jburrill** [comment]
Same issue here with fresh install of 2.4.4.sp2 on RHEL 6
`INFO   | jvm 1    | 2017/01/30 17:06:19 | Caused by: java.lang.NullPointerException`
`INFO   | jvm 1    | 2017/01/30 17:06:19 | 	at org.gluu.oxtrust.action.UpdatePersonAction.save(UpdatePersonAction.java:168)`

**Comment by nikohd** [comment]
Same issue here fresh installed 2.4.4.sp2, no issues on 3.0.0
