### ISSUE TITLE
Gluu 3.0.0 oxTrust UI | Unble to create Trust Relationship

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#416]
I'm unable to create Trust Relationship from UI and getting error "contact your administrator..."

Error in oxtrust_persistance.log

 at java.lang.Thread.run(Thread.java:745)
Caused by: javax.faces.view.facelets.TagException: //opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-4829664269322088753.dir/webapp/trustmanager/addTrustRelationship.xhtml @62,142 <ox:createSPMetadataDialog> Tag Library supports namespace: http://java.sun.com/jsf/composite/ox, but no tag was defined for name: createSPMetadataDialog

Build Details
gluu-server-3.0.0                                     35-ALPHA1~trusty+Ub14.04                            amd64        Gluu Server Community Edition

OS Version: Ubuntu 14.04 64 bit

**Comment by sahiliamsso** [comment]
reproducible on BETA build
root@ubuntu:/opt# dpkg -l|grep gluu-server
ii  gluu-server-3.0.0                                     2-BETA1~trusty+Ub14.04                              amd64        Gluu Server Community Edition

**Comment by uboznikov** [comment]
@shekhar16 Fix to #353 in `addTrustRelationship.xhtml` causes this issue.

[oxTrust/issues/353 ; Added None metadata location option and sp metadata](https://github.com/GluuFederation/oxTrust/commit/9e935fd45e24d906707de7a44b600078114f9e59)

**Comment by shekhar16** [comment]
@sahiliamsso @uboznikov  I think  one more file commit (.https://github.com/GluuFederation/oxTrust/commit/cd8664ab2c40ae9b5e375c18200ff7209a5bd2fb)       in issue  (https://github.com/GluuFederation/oxTrust/issues/353)  is not included in the build

**Comment by zamilskhan** [comment]
Error on clicking `Add Relationship` in build  luu-server-3.0.0.x86_64 2-BETA1.centos6

```
2016-12-19 23:15:35,967 ERROR [org.jboss.seam.exception.Exceptions] handled and logged exception
javax.servlet.ServletException: //opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-2035372324980924652.dir/webapp/trustmanager/addTrustRelationship.xhtml
 @62,142 <ox:createSPMetadataDialog> Tag Library supports namespace: http://java.sun.com/jsf/composite/ox, but no tag was defined for name: createSPMetadataDialog
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.faces.view.facelets.TagException: //opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-2035372324980924652.dir/webapp/trustmanager/addTrus
tRelationship.xhtml @62,142 <ox:createSPMetadataDialog> Tag Library supports namespace: http://java.sun.com/jsf/composite/ox, but no tag was defined for name: createSPMe
tadataDialog
        at com.sun.faces.facelets.compiler.CompilationManager.pushTag(CompilationManager.java:304)
        at com.sun.faces.facelets.compiler.SAXCompiler$CompilationHandler.startElement(SAXCompiler.java:259)
qq

**Comment by sahiliamsso** [comment]
It seems to be working in gluu-server-3.0.0_4-BETA1~trusty+Ub14.04_amd64.deb. I am able to open  "Add Trust Relationship" screen but unable to create Trusted Relationship with uploading metadata file. 
```
2016-12-21 01:13:23,959 ERROR [org.gluu.oxtrust.ldap.service.Shibboleth3ConfService] Failed to read metadata file '/opt/shibboleth-idp/metadata/23DF70166DAEA8C80002096E7A2B00068A5D4374-sp-metadata.xml'
java.io.FileNotFoundException: File '/opt/shibboleth-idp/metadata/23DF70166DAEA8C80002096E7A2B00068A5D4374-sp-metadata.xml' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.isFederationMetadata(Shibboleth3ConfService.java:895)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Let me know if you need more information.

**Comment by yurem** [comment]
Can you manually install latest identity.war from here http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0-SNAPSHOT/oxtrust-server-3.0.0-SNAPSHOT.war into any beta1 build?

**Comment by mzico** [comment]
@yurem : Tried this 3.0.0 snapshot for oxtrust. Same issue: http://pastebin.com/KzdXxg7i

**Comment by shekhar16** [comment]
Fixed.

**Comment by mzico** [comment]
@shekhar16 @sahiliamsso : It's not fixed. Stack trace: http://pastebin.com/U01DGuRL

I am using this version of oxTrust: 

```
GLUU.root@proxy:/opt/jetty-9.3/temp# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-7773062947981043447.dir/webapp/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.0.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: f1f50
Implementation-Vendor-Id: org.xdi
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9

GLUU.root@proxy:/opt/jetty-9.3/temp#
```

**Comment by shekhar16** [comment]
@mzico @sahiliamsso can u please , tell me have u tested it with latest  code?

**Comment by shekhar16** [comment]
and please share metadata.xml file?

**Comment by mzico** [comment]
@shekhar16 : Here is a sample metadata attached which you can try to use for creating Trust relationship. 

[SP_sample_metadata.zip](https://github.com/GluuFederation/oxTrust/files/675898/SP_sample_metadata.zip)

**Comment by shekhar16** [comment]
@uboznikov Please check your code it is regarding file upload of metadata , you were uploading it on temp folder and checking in metadata folder Due this reason  it is throwing exception .Please look into this.

**Comment by uboznikov** [comment]
I have created new issue. Please do not mix use cases.

**Comment by shekhar16** [comment]
@uboznikov Can we close this issue?

**Comment by uboznikov** [comment]
@shekhar16 If @sahiliamsso has it fixed in his testing then I think this issue can be closed. Thanks.

**Comment by sahiliamsso** [comment]
Closing this issue as initial issue of creating Trust relationship is resolved. We have opened another issue (https://github.com/GluuFederation/oxTrust/issues/428) for metadata unable to upload in TR.
