### ISSUE TITLE
"System error" upon attempt to create user via oxTrust on freshly installed instance

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#447]
Environment:
Ubuntu 14.04, Gluu CE 2.4.4 SP2 (installed from `gluu-server-2.4.4.2_6-1~trusty+Ub14.04_amd64.deb` of 2016-11-07 (which is the latest available stable package))

Steps to reproduce:
1. Log in to web UI as admin user
2. Move to "Users -> Add person"
3. Fill in all fields on the page required to create a simple user entry with default fields; provide "active" for "User status" field (for some reason there is no drop-down list to choose value from)
4. Click the "Update" button to finalize the creation.

Result:
"System error" message appears, user is not created, java exception is logged to `wrapper.log` (please see full text [here](https://github.com/GluuFederation/oxTrust/files/715352/user_creation_excptn.txt)):

```
INFO   | jvm 1    | 2017/01/11 12:18:13 | Jan 11, 2017 12:18:12 PM com.sun.faces.lifecycle.InvokeApplicationPhase execute
INFO   | jvm 1    | 2017/01/11 12:18:13 | WARNING: #{updatePersonAction.save}: java.lang.NullPointerException
INFO   | jvm 1    | 2017/01/11 12:18:13 | javax.faces.FacesException: #{updatePersonAction.save}: java.lang.NullPointerException
INFO   | jvm 1    | 2017/01/11 12:18:13 | 	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:117)
INFO   | jvm 1    | 2017/01/11 12:18:13 | 	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
INFO   | jvm 1    | 2017/01/11 12:18:13 | 	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:786)
INFO   | jvm 1    | 2017/01/11 12:18:13 | 	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1251)
```

**Comment by sahiliamsso** [comment]
I'm able to create user via oxtrust in 2.4.4.sp3

**Comment by mzico** [comment]
Problem persist in 2.4.4.2

**Comment by shekhar16** [comment]
It is already fixed in 2.4.4.2.

**Comment by mzico** [comment]
@shekhar16 : 

Here are two reports on 2.4.4.2: 

1. https://support.gluu.org/access-management/3670/fresh-gluu-server-2442-install-on-ubuntu-1604-cant-create-users-via-oxtrust-gui/

2. https://support.gluu.org/identity-management/3671/cannot-create-new-user/

**Comment by mzico** [comment]
Tried latest 2.4.4.2 ( ** ): It's working. 

(**) 
GLUU.root@idp:~# cat /opt/tomcat/webapps/oxauth/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxAuth Server
Implementation-Version: 2.4.4.sp3
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: a4faf1c8915c628e5d3826cbf7bb5923f9dd3eea
Archiver-Version: Plexus Archiver

GLUU.root@idp:~# cat /opt/tomcat/webapps/identity/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.4.sp2
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: bcdae
Archiver-Version: Plexus Archiver


@zamilskhan  and @aliaksander-samuseu : Please feel free to test in 3.0.0

**Comment by shekhar16** [comment]
Fixed in repo 2.4.4.2 sp2.

**Comment by gdstr** [comment]
![image](https://cloud.githubusercontent.com/assets/22984638/22350650/ebbf294a-e414-11e6-9331-1bb1f4c6297b.png)

still not fixed in repo 2.4.4.sp2!   

I followed the exact instruction (https://www.gluu.org/docs/deployment/ubuntu-xenial/)

on a total fresh Ubunt 16.04 server

**Comment by yurem** [comment]
@gdstr Unfortunately we can't update SP2. We already released it with this bug! But we need to fix it in SP3.

Is it works fine in SP3 current build: http://ox.gluu.org/maven/org/xdi/oxtrust-server/2.4.4.sp3/oxtrust-server-2.4.4.sp3.war ?

Is it work in 3.0,.0 beta build http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0-SNAPSHOT/oxtrust-server-3.0.0-SNAPSHOT.war ?

**Comment by dashirov-ga** [comment]
How can this component be deployed on top of the sp2 installation? When should sp3 artifacts be expected in the apt repository?

**Comment by zamilskhan** [comment]
@yurem I will test and update you.

**Comment by jburrill** [comment]
Latest 2.4.4.sp2 on RHEL 6 and Ubuntu 16.04 both contain this error.  Awaiting the fix with anticipation.

**Comment by jburrill** [comment]
Note: a workaround is to Import a User.  That works, just fine: [see Gluu Docs » User Managment »	Import XLS File](https://www.gluu.org/docs/user-management/xlsfile/).  And once the user is imported that user can be updated, added to groups, etc.  Go figure!

**Comment by shekhar16** [comment]
@yurem  fixed in sp3 branch.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 @yurem 

I can confirm it's fixed, but still there is one more problem (imo). During both user creation and editing, if non-email-kind of string is provided in "Email" field (which is in the list by default), like string without "@", or string ending with "@" (without domain part after it), operation fails, and user is redirected to home page with ambiguous "System error" message. That's not correct behaviour at all, he must stay on the page, all his input preserved, and UI just need to ask him to correct the value.

Below is what in `wrapper.log` when this happens:

```
Here is the error:

INFO   | jvm 1    | 2017/02/09 19:53:29 | javax.faces.FacesException: #{updatePersonAction.save}: org.gluu.oxtrust.model.exception.SCIMDataValidationException: The value 'dfdfdf@' is not a well-formed email.
INFO   | jvm 1    | 2017/02/09 19:53:29 |  at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:117)
INFO   | jvm 1    | 2017/02/09 19:53:29 |  at javax.faces.component.UICommand.broadcast(UICommand.java:315)
INFO   | jvm 1    | 2017/02/09 19:53:29 |  at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:786)
INFO   | jvm 1    | 2017/02/09 19:53:29 |  at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1251)
INFO   | jvm 1    | 2017/02/09 19:53:29 |  at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
INFO   | jvm 1    | 2017/02/09 19:53:29 |  at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
INFO   | jvm 1    | 2017/02/09 19:53:29 |  at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
INFO   | jvm 1    | 2017/02/09 19:53:29 |  at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
```

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxCore/commit/8b79f45ae72f27b1f4b2c8f5cdce895996c1bd08

**Comment by aliaksander-samuseu** [comment]
It's fixed in the latest (snapshot) 2.4.4 SP3 identity.war
