### ISSUE TITLE
User entry created via oxTrust lacks "eduPerson" objectclass

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#499]
Environment:
CentOS 7.3.1611, Gluu CE 3.0.1-2-1

Steps to reproduce:
1. Log in to web UI as admin user
2. Move to "Users -> Manage People" page and click "Add person" button there
3. Fill in all fields presented to you by default on the page, click the "Add" button
4. Find the user you've just created using search feature again and try to add "eduPersonAffiliation" attribute to it (or any other `edu*` attribute)

Result:
"Failed to add new person" error appears, and Java exception is registered in `oxtrust.log` (full text is [here](https://github.com/GluuFederation/oxTrust/files/817842/useradd-fails.txt)):

```
2017-03-02 11:10:18,257 ERROR [qtp2008017533-15] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:229) - Failed to add new person @!59AB.CEE3.FA78.5B92!0001!15BC.2D50!0000!A270.1BBB.6240.BB69
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!59AB.CEE3.FA78.5B92!0001!15BC.2D50!0000!A270.1BBB.6240.BB69,ou=people,o=@!59AB.CEE3.FA78.5B92!0001!15BC.2D50,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:97) ~[oxLdap-3.0.1.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxLdap-3.0.1.jar:?]

...

Caused by: com.unboundid.ldap.sdk.LDAPException: attribute 'eduPersonAffiliation' not allowed
        at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:1959) ~[unboundid-ldapsdk-3.1.1.jar:3.1.1]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:751) ~[unboundid-ldapsdk-3.1.1.jar:3.1.1]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:682) ~[unboundid-ldapsdk-3.1.1.jar:3.1.1]
        at org.gluu.site.ldap.OperationsFacade.addEntry(OperationsFacade.java:481) ~[oxLdap-3.0.1.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:92) ~[oxLdap-3.0.1.jar:?]
        ... 109 more
```

It happens because user entries created in web UI doesn't have `eduPerson` objectclass added to them. At the same time, entries created by CR has this objectclass added and issue doesn't happen for them.

Expected result:
User entries created by CR and via web UI have the same set of objectclasses.

**Comment by shekhar16** [comment]
@yurem I checked the issue, and  found its a oblect class violation,So can u please advice.Here is the ldap error :- 
LDAPException(resultCode=65 (object class violation), errorMessage='attribute 'eduPersonAffiliation' not allowed', diagnosticMessage='attribute 'eduPersonAffiliation' not allowed')

**Comment by yurem** [comment]
Fixed in master and in 3.0.2: https://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.2/oxtrust-server-3.0.2.war

**Comment by mzico** [comment]
@yurem @aliaksander-samuseu @shekhar16  : In my testing, ePSA attribute is still throwing error. 

Here is what I did: 

- A base installation of 3.0.1
- Got 3.0.2 identity war; pushed that inside. 
```
GLUU.[root@login ~]# find / -name 'MANIFEST.MF'
/opt/jetty-9.3/temp/jetty-localhost-8081-oxauth.war-_oxauth-any-9063762506729845771.dir/webapp/META-INF/MANIFEST.MF
/opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-4353679418795622121.dir/webapp/META-INF/MANIFEST.MF
/opt/jetty-9.3/temp/jetty-localhost-8081-oxauth.war-_oxauth-any-1179098484035632508.dir/webapp/META-INF/MANIFEST.MF
/opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1828901348358485404.dir/webapp/META-INF/MANIFEST.MF
/opt/jetty-9.3/temp/jetty-localhost-8086-idp.war-_idp-any-487686439714018246.dir/webapp/META-INF/MANIFEST.MF
GLUU.[root@login ~]# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-4353679418795622121.dir/webapp/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.0.2
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 1910a
Implementation-Vendor-Id: org.xdi
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9

GLUU.[root@login ~]# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1828901348358485404.dir/webapp/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.0.2
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 1910a
Implementation-Vendor-Id: org.xdi
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9

GLUU.[root@login ~]#
```
- Restarted all services ( solserver, identity, oxauth, httpd and idp )
- Tried to 'enable' eduPersonScopedAffiliation from oxTrust. 
- Whenever I clicked on this attribute, oxTrust is throwing error: 
- Stack trace ( oxtrust.log ): http://pastebin.com/81Hrn5JE
- Screenshot: 

![screenshot_12](https://cloud.githubusercontent.com/assets/7156097/23613647/f72ac01a-0245-11e7-9a86-5b9e2d17d7aa.png)

**Comment by shekhar16** [comment]
@mzico  I think we need to add ePSA  in schema.
Same issue reproduced for other attributes aswel which are not defined in schema eduPersonAssurance.
@yurem any suggestions.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/24083542/bffac9be-0cfe-11e7-914c-c2f38014ffd3.png)

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/24083556/1e770dae-0cff-11e7-89d1-d18c3935c113.png)

**Comment by aliaksander-samuseu** [comment]
@shekhar16 @yurem 

What is status of this? I've tried both latest deb 2.4.4 SP3 updater and snapshot oxtrust.war, and neither of them adds **eduPerson** class to user entries created in web UI.

**Comment by nynymike** [comment]
I don't think `eduPerson` should be the default anymore. But there should be a process for adding the `eduPerson` objectclass for those who want it.

**Comment by aliaksander-samuseu** [comment]
@shekhar16 @nynymike 

Just a bit of update. I did a test in 2.4.4SP3 (latest oxTrust snapshot) and 3.0.1 (latest 3.0.2 oxTrust snapshot):

1. `eduPerson` is included in list of objectclasses that should be added to objects (the one you can check on JSON configuration page in web UI) in both
2. When users created in web UI, in 3.0 it adds `eduPerson` now, but in 2.4.4 it still doesn't

Not sure which one should be perceived as correct behaviour, taking into account Mike's comment above.

**Comment by shekhar16** [comment]
@aliaksander-samuseu  I don't have any idea about why edusPerson attribute's removed from ldap schema file.@yurem any idea..

**Comment by nynymike** [comment]
`eduPerson` is not needed by most customers. We can ship with the schema and attribute metadata, but it should be the default objectclass for a person.  One thing I noticed is that eduPersonScopedAffiliation is not part of the openldap schema. This attribute needs to be added, and it needs to be added to the eduPerson objectclass. Could this be the problem?

**Comment by shekhar16** [comment]
@nynymike I checked there are few eduperson objectclass's attributes are still in openldap but not declared in schema. That's why this issue is occurred.

**Comment by nynymike** [comment]
We should be using this one:

https://spaces.internet2.edu/display/macedir/OpenLDAP+eduPerson

**Comment by nynymike** [comment]
Moved this issue here: https://github.com/GluuFederation/community-edition-setup/issues/283

**Comment by aliaksander-samuseu** [comment]
@shekhar16 @yurem 

Was the fix also ported to 2.4.4 packages?

**Comment by nynymike** [comment]
Alex this is not a priority. It would be better to document the workaround for now.
