### ISSUE TITLE
VTL identifier wrong in Shibboleth velocity templates

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#761]
VTL identifier variables should be declared with '$'. Instead they are with '%' now. 
Screenshot attached of attribute-resolver.xml.vm; which is prohibiting Gluu Server to load data in real configuration files. 

![screenshot_1](https://user-images.githubusercontent.com/7156097/32393548-eb6237a6-c0a7-11e7-97cb-d82f9fb27dac.png)
 
All velocity templates of Shibboleth in 3.x onward should be changed like above.

**Comment by mzico** [comment]
done. 
https://github.com/GluuFederation/oxTrust/commit/09f9ec724b68ea11d7c20c6ca6761dd19d854ab3

**Comment by dmogn** [comment]
Done.

**Comment by sahiliamsso** [comment]
Still seeing % instead of $

cat ./opt/gluu/jetty/identity/conf/shibboleth3/idp/attribute-resolver.xml.vm

![image](https://user-images.githubusercontent.com/21104811/33769364-f2b2bdd2-dc4f-11e7-8541-2361f181f9eb.png)


Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.2-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: a4fd8c2b53412640f9d32b6d91bd21614873b6ff
Implementation-Vendor-Id: org.xdi
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121

**Comment by mzico** [comment]
I don't know what happened to this ( https://github.com/GluuFederation/oxTrust/commit/09f9ec724b68ea11d7c20c6ca6761dd19d854ab3 ) changes in latest build. @yurem : thought?

**Comment by dmogn** [comment]
Hm... sorry, it's my commit.

**Comment by dmogn** [comment]
Fixed.

**Comment by dmogn** [comment]
@yurem  - could you review this commit
https://github.com/GluuFederation/oxTrust/commit/6551d0f4fac2a99cff837ea3af4b587eb5ea911f#diff-d581b363c369ce122be6b67604c4ddc7

**Comment by yurem** [comment]
@dmogn I offer to use generic IDP3 approach via: https://github.com/GluuFederation/community-edition-setup/blob/master/static/idp3/conf/ldap.properties
We should not hardcore LDAP connection properties in attribute-resolver.xml

I offer to revert this update: https://github.com/GluuFederation/oxTrust/commit/6551d0f4fac2a99cff837ea3af4b587eb5ea911f#diff-d581b363c369ce122be6b67604c4ddc7

@mzico Can you check if TR work fine in beta3?

**Comment by yurem** [comment]
@mzico reopen it if needed

**Comment by dmogn** [comment]
Original issue point is not solved yet. In process.

**Comment by yurem** [comment]
@dmogn Can you explain what we need to do for this?
