### ISSUE TITLE
Add Detail to U2F

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#823]
![image](https://user-images.githubusercontent.com/3717101/35455358-326f3596-0297-11e8-82bc-3d973c0e3b48.png)

* Show oxid in the table
* oxid should be a link to show the raw LDAP data

**Comment by shekhar16** [comment]
Right now we had implemented as per below info

For Fido Records : 
1) Super gluu Devices 
Nickname = Device name (Stored in Device Data.)
modality = "Super-Gluu Device";
Date Added : Date of creation of record.

2) other Fido devices
nickName = "U2F"
modality = "U2F device";
Date Added : Date of creation of record.

For oxExternalUid Records : 
Nickname = String's first part (before : )
Modality = String's second part (After : )
Date Added = blank as there is no info in records set.


Now as per issue description should I update the code.Here is my understandings.Please let me know your comments.
1) Should I add new column for Oxid
2) in other fido devices (exclude super gluu)  modality = USB Token

**Comment by nynymike** [comment]
Screenshot of objectclass `oxDeviceRegistration`: 

![image](https://user-images.githubusercontent.com/3717101/35641353-a0fb3f9a-0685-11e8-9087-64caae5b3381.png)

1. For the table, can we use this mapping:
* oxid  :  ID
* createDate : Date Added
* oxNickName :  "Nickname"
* (LDIF for entry) : "Raw Data"

**Comment by shekhar16** [comment]
![image](https://user-images.githubusercontent.com/15937500/36076399-a128345a-0f81-11e8-8919-a7d86e6ceab1.png)

**Comment by shekhar16** [comment]
Oxid Link Pop

![image](https://user-images.githubusercontent.com/15937500/36076417-d4dbaf84-0f81-11e8-8426-09f10ca73d82.png)

**Comment by shekhar16** [comment]
Please let me know if we need to add or correct something in above pages.

**Comment by nynymike** [comment]
The application field is mysterious. Where is that coming from? 

![image](https://user-images.githubusercontent.com/3717101/36076610-2adbebe6-0f24-11e8-8989-f90c3c6a21c9.png)

![image](https://user-images.githubusercontent.com/3717101/36076638-73ddb536-0f24-11e8-930a-0f098d46097b.png)

Also, what about additional attributes that may be present for other types of FIDO devices, like mobile and biometric. I think it would be better to just get a dump of all the data available for the entry and print it to some non-editable text format for viewing.

**Comment by shekhar16** [comment]
All the values from ldap has been listed in popup.
![image](https://user-images.githubusercontent.com/15937500/36077681-df2dcb68-0f93-11e8-8f89-ea92ea98d864.png)

**Comment by nynymike** [comment]
If new attributes are added to the objectclass, will they be displayed?  This is important because new FIDO devices will have new metadata.

**Comment by yurem** [comment]
Dialog looks fine. I offer to return back "Application" field. It's part of U2F protocol. Here is [description](https://developers.yubico.com/U2F/App_ID.html).

One more comment about "Device Registration Conf". Can we use same JS library which we uses in JSON configuration page to display this in human-oriented format.

Mike, Should we show all inputs as read-only?

**Comment by shekhar16** [comment]
@nynymike @yurem In any case if we add new attribute we need to add its entry on UI page or any other file.

**Comment by nynymike** [comment]
**should we show all inputs as read-only?**

I'd like to have a way to show all the data that is stored in the database about this FIDO credential.  I see it as likely that new FIDO devices will require new FIDO attributes, and it would be nice if oxTrust had a way to at least show it to the oxTrust admin

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/37168154-f91241f4-2329-11e8-8e10-1cc4805e7805.png)

**Comment by sahiliamsso** [comment]
![image](https://user-images.githubusercontent.com/21104811/37439760-a50fddc8-281f-11e8-9b3d-fe34a0293f50.png)
 still don't see the required details.

Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.3-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 9fe922740002e5a7b49736f6acf2acac23b46731
Implementation-Vendor-Id: org.xdi
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121

**Comment by shekhar16** [comment]
@sahiliamsso can u please explain which details u want to see?

**Comment by sahiliamsso** [comment]
ID column is missing.

**Comment by shekhar16** [comment]
@yurem  the code is not merged in oxtrust_ 3.1.3 version branch

**Comment by yurem** [comment]
@shekhar16 which changes do you mean? We merged changes from PR #895 already.

![screenshot](https://user-images.githubusercontent.com/6104200/37552266-99b82238-29c2-11e8-9150-2a6991bbe4e9.png)

**Comment by shekhar16** [comment]
in master branch it is working as expected here is snapshot
![image](https://user-images.githubusercontent.com/15937500/37552278-db422996-29d7-11e8-9560-3c7b17cbdf6a.png)

**Comment by shekhar16** [comment]
I think https://github.com/GluuFederation/oxTrust/commit/36fc658d8645195dcf0b7f92b3f5e63303f27d2c  is not merged.

**Comment by yurem** [comment]
ok, I merged it. Please notify me if you need to merge specific commit if it's not part of PR.
