### ISSUE TITLE
Attributes can't be removed/detached from user accounts via oxTrust

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#96]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.1-2

Preconditions:
1) Fresh installation of Gluu CE
2) Regular user account exists in the system.
3) Feature "User Can Edit Own Profile" on the "Configuration->Organization Configuration" page is enabled
4) Authentication against internal LDAP database is used (though it was confirmed that issue can be reproduced for CR-created accounts authenticating against back-end LDAP)

Steps to reproduce:
1) Log in to oxTrust web UI as an admin user
2) Move to the "Users"->"Manage People" page
3) Add "Locale" attribute (was confirmed for several other too) to the user and assign it some value; click "Update" button 
4) While editing the same user, click the "cross" button next to "Locale" attribute in list of user's attributes to remove it from the list, and click "Update" button
5) Move out to some other page, return and open the user again

Result:
On step 4) it first appears that attribute was detached from the user account; but on step 5) it becomes clear that attribute is still there. Its value can be changed (but not to an empty string, in this case previous value will be preserved), but looks like it's impossible to detach/remove it from user from within oxTrust (the only way is to edit the user's object in the LDAP. The same result is seen when user's attributes is modified on the "Personal->Profile" page.
See attached picture (please also note an "accompanying" issue shown on step 4b):
![attributes-delete](https://cloud.githubusercontent.com/assets/11802046/9050501/da1b8684-3a56-11e5-9540-f1098b8b4faf.png)

**Comment by mzico** [comment]
Bug persist in 2.3.2 release.

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxTrust/commit/dded283359817137e5b1c7f17d28e98a5a868b9c

**Comment by willow9886** [comment]
@yurem: @aliaksander-samuseu commented on this on trello a few days after the bug was closed... He said..

"Yuriy, it indeed was fixed for the user editor page, but the issue still persists on the profile page (when feature "User Can Edit Own Profile" on the "Organization Configuration" page is enabled they can edit their own profile). Please refer to original description of the issue on github for details: GluuFederation/oxTrust: Issue #96 I'm attaching picture from there for your convenience, all the issues depicted on the lower row of screenshots still persist. Can't see any errors in logs." 

See screenshot below:

![](https://trello-attachments.s3.amazonaws.com/54e640b2c6b449f424dc8382/563b99f08e0974aa2e893cf6/x/f06ade521df229c4d08452f47762cea9/attr-remov-error-up.png)

**Comment by mzico** [comment]
Fixed in 2.4.1
